
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDrightNOTleftPLUSMINUSleftTIMESDIVIDEnonassocBOOLNUMBERnonassocLPARENRPARENAND BOOL DIVIDE LPAREN MINUS NOT NUMBER OR PLUS RPAREN TIMESexpr : expr PLUS term\n            | expr MINUS termexpr : termterm : term TIMES factor\n            | term DIVIDE factorterm : factorfactor : LPAREN expr RPARENfactor : logicallogical : logical AND logical\n               | logical OR logicallogical : NOT logicallogical : BOOLlogical : NUMBER'
    
_lr_action_items = {'LPAREN':([0,4,9,10,11,12,],[4,4,4,4,4,4,]),'NOT':([0,4,6,9,10,11,12,14,15,],[6,6,6,6,6,6,6,6,6,]),'BOOL':([0,4,6,9,10,11,12,14,15,],[7,7,7,7,7,7,7,7,7,]),'NUMBER':([0,4,6,9,10,11,12,14,15,],[8,8,8,8,8,8,8,8,8,]),'$end':([1,2,3,5,7,8,16,17,18,19,20,21,22,23,],[0,-3,-6,-8,-12,-13,-11,-1,-2,-4,-5,-7,-9,-10,]),'PLUS':([1,2,3,5,7,8,13,16,17,18,19,20,21,22,23,],[9,-3,-6,-8,-12,-13,9,-11,-1,-2,-4,-5,-7,-9,-10,]),'MINUS':([1,2,3,5,7,8,13,16,17,18,19,20,21,22,23,],[10,-3,-6,-8,-12,-13,10,-11,-1,-2,-4,-5,-7,-9,-10,]),'RPAREN':([2,3,5,7,8,13,16,17,18,19,20,21,22,23,],[-3,-6,-8,-12,-13,21,-11,-1,-2,-4,-5,-7,-9,-10,]),'TIMES':([2,3,5,7,8,16,17,18,19,20,21,22,23,],[11,-6,-8,-12,-13,-11,11,11,-4,-5,-7,-9,-10,]),'DIVIDE':([2,3,5,7,8,16,17,18,19,20,21,22,23,],[12,-6,-8,-12,-13,-11,12,12,-4,-5,-7,-9,-10,]),'AND':([5,7,8,16,22,23,],[14,-12,-13,-11,-9,14,]),'OR':([5,7,8,16,22,23,],[15,-12,-13,-11,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,],[1,13,]),'term':([0,4,9,10,],[2,2,17,18,]),'factor':([0,4,9,10,11,12,],[3,3,3,3,19,20,]),'logical':([0,4,6,9,10,11,12,14,15,],[5,5,16,5,5,5,5,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS term','expr',3,'p_expr_addsub','EComplejas.py',54),
  ('expr -> expr MINUS term','expr',3,'p_expr_addsub','EComplejas.py',55),
  ('expr -> term','expr',1,'p_expr_term','EComplejas.py',59),
  ('term -> term TIMES factor','term',3,'p_term_muldiv','EComplejas.py',63),
  ('term -> term DIVIDE factor','term',3,'p_term_muldiv','EComplejas.py',64),
  ('term -> factor','term',1,'p_term_factor','EComplejas.py',68),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor_parens','EComplejas.py',72),
  ('factor -> logical','factor',1,'p_factor_logical','EComplejas.py',76),
  ('logical -> logical AND logical','logical',3,'p_logical_andor','EComplejas.py',80),
  ('logical -> logical OR logical','logical',3,'p_logical_andor','EComplejas.py',81),
  ('logical -> NOT logical','logical',2,'p_logical_not','EComplejas.py',85),
  ('logical -> BOOL','logical',1,'p_logical_bool','EComplejas.py',89),
  ('logical -> NUMBER','logical',1,'p_logical_number','EComplejas.py',93),
]
